Repository google/testrun, pull requests merged in 2024-03, with the labels that each got.

#299 Fix text; fix gaps
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.scss
Labels: bug, ui

#304 326951948: (fix) [a11y] add accessible names for welcome modal and buttons
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
  modules/ui/src/app/components/version/version.component.ts
Labels: bug, ui

#301 Fix focus style when consent pop-up closed
  modules/ui/src/styles.scss
Labels: bug, ui

#298 Adds state for devices component; devices added to shared state
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/mocks/device.mock.ts
  modules/ui/src/app/pages/devices/components/device-form/device-form.component.spec.ts
  modules/ui/src/app/pages/devices/components/device-form/device-form.component.ts
  modules/ui/src/app/pages/devices/components/device-form/device.validators.ts
  modules/ui/src/app/pages/devices/device-repository.component.html
  modules/ui/src/app/pages/devices/device-repository.component.spec.ts
  modules/ui/src/app/pages/devices/device-repository.component.ts
  modules/ui/src/app/pages/devices/devices.store.spec.ts
  modules/ui/src/app/pages/devices/devices.store.ts
  modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.spec.ts
  modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.ts
  modules/ui/src/app/pages/testrun/progress.component.html
  modules/ui/src/app/pages/testrun/progress.component.spec.ts
  modules/ui/src/app/pages/testrun/progress.component.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
  modules/ui/src/app/store/state.ts
Labels: ui

#303 Return old version if request fails
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: bug, ui

#307 327410289: (feat) add protocol module
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#308 327607397: (fix) update packages to fix security issue from dependabot
  modules/ui/package-lock.json
  modules/ui/package.json
  modules/ui/src/app/app.component.scss
  modules/ui/tsconfig.json
Labels: bug, ui

#312 327324282: (fix) remove compliant high and limited statuses from filters
  modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.ts
Labels: ui

#311 325424134: (fix) change borders for results table to be visible on scrolling
  modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.scss
  modules/ui/src/app/pages/testrun/progress.component.scss
Labels: bug, ui

#316 326193923: (fix) change to prevent the callout for step 1 blinks on loading/reloading the page
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/pages/devices/device-repository.component.html
  modules/ui/src/app/store/state.ts
Labels: bug, ui

#318 327722371 (fix) make the Welcome modal appears in case the version response returns the error
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: bug, ui

#313 327161779: (fix) change get status with finished data to display a proper status on status bar
  modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.spec.ts
  modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.ts
  modules/ui/src/app/pages/testrun/progress.component.scss
Labels: bug, ui

#321 327324281: (feat) change callout messages for missing setting ports
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/model/setting.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
  modules/ui/src/app/store/state.ts
Labels: ui

#322 Consent dialog should not be closed on esc
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.ts
Labels: bug, ui

#319 Update documentation
  README.md
  docs/test/modules.md
  modules/test/dns/README.md
  modules/test/nmap/README.md
  modules/test/nmap/conf/module_config.json
  modules/test/ntp/README.md
  modules/test/protocol/README.md
  modules/test/protocol/conf/module_config.json
  modules/test/tls/README.md
Labels: docs

#323 Fix padding in menu item
  modules/ui/src/app/app.component.scss
  modules/ui/src/styles.scss
Labels: bug, ui

#327 Change progress page spinner size to small
  modules/ui/src/app/pages/testrun/progress.component.scss
Labels: bug, ui

#330 Save expand/collapse state
  modules/ui/src/app/mocks/progress.mock.ts
  modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.html
  modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.spec.ts
  modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.ts
Labels: bug, ui

#336 329086273: (fix) [a11Y] change the version button accessible name
  modules/ui/src/app/components/version/version.component.html
  modules/ui/src/app/components/version/version.component.spec.ts
  modules/ui/src/app/components/version/version.component.ts
Labels: bug, ui

#339 328175839: (fix) [a11Y] change to set focus on opening the settings panel
  modules/ui/src/app/app.component.html
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
  modules/ui/src/app/pages/settings/general-settings.component.html
Labels: bug, ui

#340 Update message
  framework/python/src/api/api.py
Labels: bug

#337 Cancelled status: empty table
  modules/ui/src/app/mocks/progress.mock.ts
  modules/ui/src/app/pages/testrun/progress.component.spec.ts
  modules/ui/src/app/pages/testrun/progress.component.ts
Labels: bug, ui

#334 Remove cancel on download
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.spec.ts
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.ts
Labels: bug, ui

#345 329834205: (fix) apply Angular tooltip to fix the long text issue on hover
  modules/ui/src/app/components/download-report-pdf/download-report-pdf.component.html
  modules/ui/src/app/components/download-report-pdf/download-report-pdf.component.spec.ts
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.html
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
  modules/ui/src/app/components/download-report/download-report.component.html
  modules/ui/src/app/components/download-report/download-report.component.spec.ts
  modules/ui/src/app/components/download-report/download-report.component.ts
  modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.html
  modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.ts
  modules/ui/src/app/pages/testrun/progress.component.spec.ts
Labels: bug, ui

#174 Add virtual machine install guide
  docs/get_started.md
  docs/virtual_machine.md
Labels: docs

#350 328405692: (fix) [a11y] add validation, error messages, hints for filters modal
  modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.html
  modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.scss
  modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.spec.ts
  modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.ts
Labels: bug, ui

#351 330699330: (fix) change styles to prevent unexpected space on pages with welcome modal
  modules/ui/src/styles.scss
Labels: bug, ui

#349 Bump dependabot alerts
  modules/ui/package-lock.json
Labels: dependencies

#354 fix: update outdated packages to fix security issues
  modules/ui/package-lock.json
  modules/ui/package.json
Labels: bug, dependencies

#356 330700777: (fix) update styles for fixing ui focus border issues
  modules/ui/src/app/components/device-item/device-item.component.scss
  modules/ui/src/app/components/download-report/download-report.component.scss
  modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.scss
  modules/ui/src/app/pages/reports/history.component.scss
  modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.scss
  modules/ui/src/app/pages/testrun/progress.component.scss
Labels: bug, ui

#357 331364084: (fix) update label and placeholder for started modal filter
  modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.html
Labels: bug, ui

#358 328745809: (fix) [a11y] change styles to status card and device item or meet requirements dyslexia
  modules/ui/src/app/components/device-item/device-item.component.scss
  modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.scss
Labels: bug, ui

#359 331572594: (fix) [a11Y] GAR 1.13 The firmware field validation
  modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.html
  modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.spec.ts
Labels: bug, ui
