Repository google/testrun, pull requests merged in 2024-01, with the labels that each got.

#217 Remove unnecessary OUI.txt downloads
  modules/network/dhcp-1/dhcp-1.Dockerfile
  modules/network/dhcp-2/dhcp-2.Dockerfile
  modules/test/base/base.Dockerfile
  modules/test/conn/conn.Dockerfile
Labels: bug

#216 Add check before launching UI
  framework/python/src/core/testrun.py
Labels: bug

#211 Set owner of config file during install
  .gitignore
  cmd/install
  make/DEBIAN/postinst
Labels: bug, framework

#213 Add edit device endpoint
  cmd/package
  framework/python/src/api/api.py
  framework/python/src/common/testreport.py
  make/DEBIAN/control
  modules/ui/src/app/app-routing.module.ts
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.scss
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/components/bypass/bypass.component.spec.ts
  modules/ui/src/app/components/bypass/bypass.component.ts
  modules/ui/src/app/components/callout/callout.component.scss
  modules/ui/src/app/components/delete-form/delete-form.component.html
  modules/ui/src/app/components/delete-report/delete-report.component.spec.ts
  modules/ui/src/app/components/delete-report/delete-report.component.ts
  modules/ui/src/app/components/device-item/device-item.component.html
  modules/ui/src/app/components/device-item/device-item.component.scss
  modules/ui/src/app/components/filter-chips/filter-chips.component.html
  modules/ui/src/app/components/filter-chips/filter-chips.component.scss
  modules/ui/src/app/components/filter-dialog/filter-dialog.component.html
  modules/ui/src/app/components/general-settings/general-settings.component.html
  modules/ui/src/app/components/general-settings/general-settings.component.scss
  modules/ui/src/app/components/general-settings/general-settings.component.spec.ts
  modules/ui/src/app/components/general-settings/general-settings.component.ts
  modules/ui/src/app/components/spinner/spinner.component.scss
  modules/ui/src/app/components/version/update-dialog/update-dialog.component.html
  modules/ui/src/app/components/version/version.component.html
  modules/ui/src/app/components/version/version.component.spec.ts
  modules/ui/src/app/components/version/version.component.ts
  modules/ui/src/app/device-repository/device-form/device-form.component.html
  modules/ui/src/app/device-repository/device-form/device-form.component.scss
  modules/ui/src/app/device-repository/device-form/device-form.component.spec.ts
  modules/ui/src/app/device-repository/device-form/device-form.component.ts
  modules/ui/src/app/device-repository/device-form/device.validators.ts
  modules/ui/src/app/device-repository/device-repository.component.html
  modules/ui/src/app/device-repository/device-repository.component.spec.ts
  modules/ui/src/app/device-repository/device-repository.component.ts
  modules/ui/src/app/history/history.component.html
  modules/ui/src/app/history/history.component.scss
  modules/ui/src/app/history/history.component.spec.ts
  modules/ui/src/app/history/history.component.ts
  modules/ui/src/app/progress/progress-breadcrumbs/progress-breadcrumbs.component.html
  modules/ui/src/app/progress/progress-breadcrumbs/progress-breadcrumbs.component.scss
  modules/ui/src/app/progress/progress-breadcrumbs/progress-breadcrumbs.component.spec.ts
  modules/ui/src/app/progress/progress-breadcrumbs/progress-breadcrumbs.component.ts
  modules/ui/src/app/progress/progress-initiate-form/progress-initiate-form.component.spec.ts
  modules/ui/src/app/progress/progress-initiate-form/progress-initiate-form.component.ts
  modules/ui/src/app/progress/progress-status-card/progress-status-card.component.scss
  modules/ui/src/app/progress/progress-table/progress-table.component.html
  modules/ui/src/app/progress/progress.component.html
  modules/ui/src/app/progress/progress.component.scss
  modules/ui/src/app/progress/progress.component.spec.ts
  modules/ui/src/app/progress/progress.component.ts
  modules/ui/src/app/progress/progress.module.ts
  modules/ui/src/app/services/state.service.spec.ts
  modules/ui/src/app/services/state.service.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
  modules/ui/src/index.html
  modules/ui/src/theming/theme.scss
Labels: framework

#227 Add edit device endpoint to release v1.1.1
  cmd/package
  framework/python/src/api/api.py
  framework/python/src/common/testreport.py
  make/DEBIAN/control
Labels: bug

#234 Adds download button to Testrun page
  framework/python/src/common/session.py
  framework/python/src/common/testreport.py
  framework/python/src/test_orc/test_orchestrator.py
Labels: bug

#245 322476587: (fix) change to set default selected value on close panel
  modules/ui/src/app/components/general-settings/general-settings.component.ts
Labels: bug, ui
