Repository google/testrun, pull requests merged in 2024-05, with the labels that each got.

#424 Adds delete certificate
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/mocks/certificate.mock.ts
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.html
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.spec.ts
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.ts
  modules/ui/src/app/pages/certificates/certificates.component.html
  modules/ui/src/app/pages/certificates/certificates.component.spec.ts
  modules/ui/src/app/pages/certificates/certificates.component.ts
  modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.spec.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#422 Remove in progress status after discovery
  framework/python/src/core/testrun.py
Labels: bug

#434 Adds class for links to track report type on download
  modules/ui/src/app/components/download-report-pdf/download-report-pdf.component.html
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.html
  modules/ui/src/app/components/download-report/download-report.component.html
  modules/ui/src/app/components/download-report/download-report.component.spec.ts
  modules/ui/src/app/components/download-report/download-report.component.ts
  modules/ui/src/app/mocks/progress.mock.ts
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.spec.ts
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.ts
Labels: ui

#436 For delete report take mac_addr from upper level
  modules/ui/src/app/mocks/progress.mock.ts
  modules/ui/src/app/mocks/reports.mock.ts
  modules/ui/src/app/model/testrun-status.ts
  modules/ui/src/app/pages/reports/history.component.ts
  modules/ui/src/app/pages/reports/reports.store.ts
Labels: ui

#435 Update dependencies
  modules/ui/package-lock.json
Labels: ui, dependencies, javascript

#432 Change API response for reports
  framework/python/src/api/api.py
  framework/python/src/common/device.py
  framework/python/src/common/testreport.py
  framework/python/src/core/testrun.py
  framework/python/src/test_orc/test_orchestrator.py
Labels: bug

#431 Adds upload certificate
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/mocks/certificate.mock.ts
  modules/ui/src/app/model/certificate.ts
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.html
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.scss
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.spec.ts
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.ts
  modules/ui/src/app/pages/certificates/certificate-upload-button/certificate-upload-button.component.html
  modules/ui/src/app/pages/certificates/certificate-upload-button/certificate-upload-button.component.scss
  modules/ui/src/app/pages/certificates/certificate-upload-button/certificate-upload-button.component.spec.ts
  modules/ui/src/app/pages/certificates/certificate-upload-button/certificate-upload-button.component.ts
  modules/ui/src/app/pages/certificates/certificates.component.html
  modules/ui/src/app/pages/certificates/certificates.component.scss
  modules/ui/src/app/pages/certificates/certificates.component.spec.ts
  modules/ui/src/app/pages/certificates/certificates.component.ts
  modules/ui/src/app/pages/certificates/certificates.store.spec.ts
  modules/ui/src/app/pages/certificates/certificates.store.ts
  modules/ui/src/app/services/notification.service.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
  modules/ui/src/styles.scss
Labels: ui

#438 Catch error on report/certificate deletion
  modules/ui/src/app/pages/certificates/certificates.store.ts
  modules/ui/src/app/pages/reports/reports.store.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: bug, ui

#440 Fix button size; fix text-overflow
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.scss
Labels: bug, ui

#439 Adds focus on next or close button when certificate is deleted
  modules/ui/src/app/pages/certificates/certificates.component.html
  modules/ui/src/app/pages/certificates/certificates.component.spec.ts
  modules/ui/src/app/pages/certificates/certificates.component.ts
  modules/ui/src/app/pages/certificates/certificates.store.spec.ts
  modules/ui/src/app/pages/certificates/certificates.store.ts
Labels: bug, ui

#400 Enable test modules for initiate test run dialog
  modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.html
  modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.spec.ts
  modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#445 fix: replace Feature Not Present to Feature Not Detected
  modules/ui/src/app/model/testrun-status.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#441 Fix alignment with steps to resolve in PDF report
  framework/python/src/common/testreport.py
  framework/python/src/common/util.py
Labels: bug

#442 Reconnecting the adapters causes disabling the settings selection
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/pages/settings/components/settings-dropdown/settings-dropdown.component.ts
  modules/ui/src/app/pages/settings/general-settings.component.ts
Labels: bug, ui

#456 Rename "history" to "reports"
  modules/ui/src/app/app-routing.module.ts
  modules/ui/src/app/pages/reports/reports-routing.module.ts
  modules/ui/src/app/pages/reports/reports.component.html
  modules/ui/src/app/pages/reports/reports.component.scss
  modules/ui/src/app/pages/reports/reports.component.spec.ts
  modules/ui/src/app/pages/reports/reports.module.ts
  modules/ui/src/app/pages/reports/reportscomponent.ts
Labels: ui

#455 Rename "device-repository" to "devices"
  modules/ui/src/app/app-routing.module.ts
  modules/ui/src/app/components/device-item/device-item.component.spec.ts
  modules/ui/src/app/pages/devices/devices-routing.module.ts
  modules/ui/src/app/pages/devices/devices.component.html
  modules/ui/src/app/pages/devices/devices.component.scss
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
  modules/ui/src/app/pages/devices/devices.module.ts
Labels: ui

#458 Change certificates endpoints
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: bug, ui

#459 UI defects are shown while using increased text spacing
  modules/ui/src/app/pages/certificates/certificate-upload-button/certificate-upload-button.component.scss
  modules/ui/src/styles.scss
Labels: bug, ui

#461 340835710: (fix) [Risk assessment] change page view when callout is visible
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss
  modules/ui/src/styles.scss
  modules/ui/src/theming/variables.scss
Labels: ui

#462 Fix style to allow screen reader to read label
  modules/ui/src/styles.scss
Labels: bug, ui

#466 339311250: (feat) delete risk profile
  modules/ui/src/app/mocks/profile.mock.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#467 341254121: (fix) [a11y] add item name for aria-labels delete and copy buttons
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.html
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts
Labels: bug, ui

#468 Make testing statuses available outside of Testing Tab
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.module.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/interceptors/loading.interceptor.ts
  modules/ui/src/app/pages/settings/general-settings.component.ts
  modules/ui/src/app/pages/testrun/progress.component.spec.ts
  modules/ui/src/app/pages/testrun/progress.component.ts
  modules/ui/src/app/pages/testrun/testrun.store.spec.ts
  modules/ui/src/app/pages/testrun/testrun.store.ts
  modules/ui/src/app/services/test-run.service.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
  modules/ui/src/app/store/state.ts
Labels: ui

#464 Validate CA certificate on FE
  modules/ui/src/app/mocks/certificate.mock.ts
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.html
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.scss
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.spec.ts
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.ts
  modules/ui/src/app/pages/certificates/certificate-upload-button/certificate-upload-button.component.html
  modules/ui/src/app/pages/certificates/certificate-upload-button/certificate-upload-button.component.ts
  modules/ui/src/app/pages/certificates/certificate.validator.ts
  modules/ui/src/app/pages/certificates/certificates.component.spec.ts
  modules/ui/src/app/pages/certificates/certificates.component.ts
  modules/ui/src/app/pages/certificates/certificates.store.spec.ts
  modules/ui/src/app/pages/certificates/certificates.store.ts
Labels: ui

#471 341901606: (fix) [GAR 1.6]: update for arrows usage on risk profile
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss
Labels: bug, ui

#469 The space is not allowed in the certificate name
  modules/ui/src/app/mocks/certificate.mock.ts
  modules/ui/src/app/pages/certificates/certificate.validator.ts
Labels: bug, ui

#472 342096458: (fix) [GAR 1.3] add focus trap to certificates panel to prevent move focus to risk profile
  modules/ui/src/app/pages/certificates/certificates.component.ts
Labels: bug, ui

#470 The focus is not moved to the snackbar with certificate validation rule
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/pages/certificates/certificates.store.spec.ts
  modules/ui/src/app/pages/certificates/certificates.store.ts
  modules/ui/src/app/services/notification.service.spec.ts
  modules/ui/src/app/services/notification.service.ts
Labels: bug, ui

#473 Adds file name in error message
  modules/ui/src/app/pages/certificates/certificates.component.ts
  modules/ui/src/app/pages/certificates/certificates.store.spec.ts
  modules/ui/src/app/pages/certificates/certificates.store.ts
Labels: bug, ui

#474 "Waiting for Device" :the snack bar appears on all pages
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/pages/testrun/progress.component.ts
  modules/ui/src/app/pages/testrun/testrun.store.spec.ts
  modules/ui/src/app/pages/testrun/testrun.store.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
Labels: bug, ui

#480 The certificate can not be uploaded
  modules/ui/src/app/services/test-run.service.ts
Labels: bug, ui

#476 Rename settings component
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.module.ts
  modules/ui/src/app/pages/settings/settings.component.html
  modules/ui/src/app/pages/settings/settings.component.scss
  modules/ui/src/app/pages/settings/settings.component.spec.ts
  modules/ui/src/app/pages/settings/settings.component.ts
Labels: ui

#477 Rename testrun component
  modules/ui/src/app/app-routing.module.ts
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/components/download-report-pdf/download-report-pdf.component.spec.ts
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
  modules/ui/src/app/components/download-report/download-report.component.spec.ts
  modules/ui/src/app/components/report-action/report-action.component.spec.ts
  modules/ui/src/app/mocks/testrun.mock.ts
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
  modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.spec.ts
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.spec.ts
  modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.html
  modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.scss
  modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.spec.ts
  modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.ts
  modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.html
  modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.scss
  modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.spec.ts
  modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.ts
  modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.html
  modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.scss
  modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.spec.ts
  modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.ts
  modules/ui/src/app/pages/testrun/testrun-routing.module.ts
  modules/ui/src/app/pages/testrun/testrun.component.html
  modules/ui/src/app/pages/testrun/testrun.component.scss
  modules/ui/src/app/pages/testrun/testrun.component.spec.ts
  modules/ui/src/app/pages/testrun/testrun.component.ts
  modules/ui/src/app/pages/testrun/testrun.module.ts
  modules/ui/src/app/pages/testrun/testrun.store.spec.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/reducers.spec.ts
Labels: ui

#484 Remove certificate if BE error happens
  modules/ui/src/app/pages/certificates/certificates.store.spec.ts
  modules/ui/src/app/pages/certificates/certificates.store.ts
Labels: bug, ui

#487 Allow stop testrun from any other page
  modules/ui/src/app/components/snack-bar/snack-bar.component.spec.ts
  modules/ui/src/app/components/snack-bar/snack-bar.component.ts
  modules/ui/src/app/pages/testrun/testrun.component.spec.ts
  modules/ui/src/app/pages/testrun/testrun.component.ts
  modules/ui/src/app/pages/testrun/testrun.store.spec.ts
  modules/ui/src/app/pages/testrun/testrun.store.ts
  modules/ui/src/app/services/notification.service.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
Labels: bug, ui

#489 The focus goes to the main page element after adding the ceriticate
  modules/ui/src/app/pages/certificates/certificates.store.spec.ts
  modules/ui/src/app/pages/certificates/certificates.store.ts
  modules/ui/src/app/services/notification.service.ts
Labels: bug, ui

#488 The snack bar with test attempt status appears if the user is not on Testing page
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
Labels: bug, ui
