Repository google/testrun, pull requests merged in 2024-02, with the labels that each got.

#239 Nmap report
  .gitignore
  framework/python/src/api/api.py
  framework/python/src/common/testreport.py
  framework/python/src/net_orc/network_validator.py
  framework/python/src/test_orc/test_orchestrator.py
  modules/test/nmap/python/src/nmap_module.py
  modules/test/nmap/python/src/run.py
  modules/test/tls/python/src/tls_module.py
  testing/unit/dns/dns.pcap
  testing/unit/dns/dns_module_test.py
  testing/unit/dns/dns_report_local.md
  testing/unit/dns/dns_report_local_no_dns.md
  testing/unit/dns/monitor.pcap
  testing/unit/dns/startup.pcap
  testing/unit/nmap/all_closed_report.md
  testing/unit/nmap/all_closed_scan_result.json
  testing/unit/nmap/nmap_module_test.py
  testing/unit/nmap/nmap_report_local.md
  testing/unit/nmap/ports_open_report.md
  testing/unit/nmap/ports_open_scan_result.json
  testing/unit/report/report.json
  testing/unit/report/report_test.py
  testing/unit/run_tests.sh
  testing/unit/tls/tls_module_test.py
Labels: framework

#263 Refactoring
  modules/ui/package-lock.json
  modules/ui/package.json
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.module.ts
  modules/ui/src/app/mocks/settings.mock.ts
  modules/ui/src/app/model/setting.ts
  modules/ui/src/app/pages/settings/components/settings-dropdown/settings-dropdown.component.html
  modules/ui/src/app/pages/settings/components/settings-dropdown/settings-dropdown.component.scss
  modules/ui/src/app/pages/settings/components/settings-dropdown/settings-dropdown.component.spec.ts
  modules/ui/src/app/pages/settings/components/settings-dropdown/settings-dropdown.component.ts
  modules/ui/src/app/pages/settings/general-settings.component.html
  modules/ui/src/app/pages/settings/general-settings.component.scss
  modules/ui/src/app/pages/settings/general-settings.component.spec.ts
  modules/ui/src/app/pages/settings/general-settings.component.ts
  modules/ui/src/app/pages/settings/only-different-values.validator.ts
  modules/ui/src/app/pages/settings/settings.store.spec.ts
  modules/ui/src/app/pages/settings/settings.store.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
  modules/ui/src/app/store/state.ts
Labels: ui

#265 Bump vite and @angular-devkit/build-angular in /modules/ui
  modules/ui/package-lock.json
  modules/ui/package.json
Labels: ui

#266 Change URL used by UI
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#268 324383967: (feat) display in progress test status
  modules/ui/src/app/model/testrun-status.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#258 Add appropriate headings
  framework/python/src/common/testreport.py
Labels: bug

#271 Enable save button when only one interface is available
  modules/ui/src/app/components/general-settings/general-settings.component.html
  modules/ui/src/app/components/general-settings/general-settings.component.spec.ts
  modules/ui/src/app/components/general-settings/general-settings.component.ts
Labels: bug, ui

#273 322355032: (feat) add high and limited compliant test statuses
  modules/ui/src/app/components/spinner/spinner.component.spec.ts
  modules/ui/src/app/model/testrun-status.ts
  modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.ts
  modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.spec.ts
  modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#276 Adds component state for reports page
  modules/ui/src/app/mocks/reports.mock.ts
  modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.spec.ts
  modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.ts
  modules/ui/src/app/pages/reports/history.component.html
  modules/ui/src/app/pages/reports/history.component.spec.ts
  modules/ui/src/app/pages/reports/history.component.ts
  modules/ui/src/app/pages/reports/reports.store.spec.ts
  modules/ui/src/app/pages/reports/reports.store.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#278 325419639: (fix) [a11y] change styles for meet GAR 2.11 for the arrow button
  modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.scss
Labels: ui

#282 324202752: (fix) device name and device model name cutting
  modules/ui/src/app/components/device-item/device-item.component.scss
Labels: ui

#281 Save button is disabled when port is no longer available
  modules/ui/src/app/pages/settings/general-settings.component.spec.ts
  modules/ui/src/app/pages/settings/general-settings.component.ts
  modules/ui/src/app/pages/settings/settings.store.spec.ts
  modules/ui/src/app/pages/settings/settings.store.ts
Labels: bug, ui

#284 324061101: (fix) [a11y] GAR 1.3 the focus is not placed to the snackbar button
  modules/ui/src/app/services/focus-manager.service.ts
  modules/ui/src/app/services/notification.service.spec.ts
  modules/ui/src/app/services/notification.service.ts
Labels: ui

#257 Add steps to resolve to dev
  framework/python/src/test_orc/test_case.py
  framework/python/src/test_orc/test_orchestrator.py
  modules/test/base/python/src/test_module.py
  modules/test/conn/conf/module_config.json
  modules/test/dns/conf/module_config.json
  modules/test/nmap/conf/module_config.json
  modules/test/ntp/conf/module_config.json
  modules/test/tls/conf/module_config.json
Labels: framework

#236 Add in progress tests to Testrun page
  framework/python/src/common/session.py
  framework/python/src/common/testreport.py
  framework/python/src/test_orc/test_case.py
  framework/python/src/test_orc/test_orchestrator.py
  framework/requirements.txt
Labels: framework

#287 324864346: (fix) [a11Y] change color for field label to fix GAR 1.14 low color contrast
  modules/ui/src/styles.scss
Labels: bug, ui

#285 Adds consent window to grant/deny GA
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.scss
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.spec.ts
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.ts
  modules/ui/src/app/components/version/update-dialog/update-dialog.component.html
  modules/ui/src/app/components/version/update-dialog/update-dialog.component.scss
  modules/ui/src/app/components/version/version.component.html
  modules/ui/src/app/components/version/version.component.scss
  modules/ui/src/app/components/version/version.component.spec.ts
  modules/ui/src/app/components/version/version.component.ts
  modules/ui/src/app/pages/reports/history.component.scss
  modules/ui/src/assets/icons/testrun_logo.svg
  modules/ui/src/index.html
  modules/ui/src/styles.scss
Labels: ui

#288 Update interfaces on settings open
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/pages/settings/general-settings.component.ts
Labels: bug, ui

#289 Show consent dialog only once per session
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/components/version/version.component.ts
Labels: ui
