Repository google/testrun, pull requests merged in 2024-07, with the labels that each got.

#564 The risk profile name of removed risk profile can not be used for another risk profile
  modules/ui/src/app/mocks/profile.mock.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
Labels: bug, ui

#565 Enables save and draft button for edit mode
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
Labels: bug, ui

#566 The validation for the multi-select questions is not shown
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
Labels: bug, ui

#567 Remove copy button
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts
Labels: ui

#569 The risk profile draft is shown in the dropdown on the Download ZIP popup; 404 error on redirect
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts
  modules/ui/src/app/mocks/profile.mock.ts
Labels: bug, ui

#563 Fix bug when saving draft profile
  framework/python/src/common/risk_profile.py
  framework/python/src/common/session.py
  modules/test/services/python/requirements.txt
  testing/unit/build.sh
  testing/unit/ntp/ntp_module_test.py
  testing/unit/report/report_test.py
  testing/unit/risk_profile/profiles/risk_profile_draft.json
  testing/unit/risk_profile/profiles/risk_profile_expired.json
  testing/unit/risk_profile/profiles/risk_profile_valid_high.json
  testing/unit/risk_profile/profiles/risk_profile_valid_limited.json
  testing/unit/risk_profile/risk_profile_test.py
  testing/unit/run.sh
  testing/unit/run_tests.sh
  testing/unit/services/reports/services_report_all_closed_local.html
  testing/unit/services/reports/services_report_local.html
  testing/unit/services/services_module_test.py
  testing/unit/unit_test.Dockerfile
Labels: bug

#570 The focus is not moved to the page headline on opening the page using the keyboard
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/pages/devices/devices.component.html
  modules/ui/src/app/pages/reports/reports.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/testrun/testrun.component.html
  modules/ui/src/app/services/focus-manager.service.spec.ts
  modules/ui/src/app/services/focus-manager.service.ts
Labels: bug, ui

#575 Remove cert from session after delete request
  framework/python/src/api/api.py
  framework/python/src/common/session.py
Labels: bug

#576 Fix error when only draft profiles are exist
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts
  modules/ui/src/app/pages/reports/reports.component.html
  modules/ui/src/app/pages/reports/reports.component.spec.ts
  modules/ui/src/app/pages/reports/reports.store.spec.ts
  modules/ui/src/app/pages/reports/reports.store.ts
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.html
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.ts
  modules/ui/src/app/pages/testrun/testrun.component.html
  modules/ui/src/app/pages/testrun/testrun.component.spec.ts
  modules/ui/src/app/pages/testrun/testrun.store.spec.ts
  modules/ui/src/app/pages/testrun/testrun.store.ts
Labels: bug, ui

#579 Focus fix; fix profile status icon
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
  modules/ui/src/app/services/focus-manager.service.spec.ts
  modules/ui/src/app/services/focus-manager.service.ts
Labels: bug, ui

#578 Support longer string answers in profile PDF
  framework/python/src/common/risk_profile.py
  framework/python/src/common/session.py
Labels: bug

#586 351758698: (fix) update app version styles to meet design on expanded nav
  modules/ui/src/styles.scss
Labels: bug, ui

#582 Update profile risk banner description
  framework/python/src/common/risk_profile.py
Labels: bug

#580 Remove skipped result
  modules/test/base/python/src/test_module.py
Labels: bug

#581 Prevent creating device with duplicate manufacturer and model
  framework/python/src/api/api.py
  framework/python/src/common/session.py
Labels: bug

#577 Remove profile from runtime once included in ZIP
  framework/python/src/test_orc/test_orchestrator.py
Labels: bug

#587 2 callouts about system settings are shown on the first run
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
Labels: bug, ui

#589 2 callouts about system settings are shown on the first run
  modules/ui/src/app/model/setting.ts
  modules/ui/src/app/pages/settings/settings.component.spec.ts
  modules/ui/src/app/pages/settings/settings.store.spec.ts
  modules/ui/src/app/pages/settings/settings.store.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
Labels: bug, ui

#592 Catch error to proceed with device creation/editing
  modules/ui/src/app/pages/devices/devices.store.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: bug, ui

#595 Add testrun.log to testing directory and fix bug with monitor
  framework/python/src/net_orc/network_orchestrator.py
  framework/python/src/test_orc/test_orchestrator.py
Labels: bug

#593 Fix step 1 callout error
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
Labels: bug, ui

#596 Feature/discard profile
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: ui

#597 Load test modules dynamically
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/mocks/device.mock.ts
  modules/ui/src/app/pages/devices/devices.component.html
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
  modules/ui/src/app/pages/devices/devices.store.spec.ts
  modules/ui/src/app/pages/devices/devices.store.ts
  modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.spec.ts
  modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.ts
  modules/ui/src/app/pages/testrun/testrun.component.html
  modules/ui/src/app/pages/testrun/testrun.component.spec.ts
  modules/ui/src/app/pages/testrun/testrun.component.ts
  modules/ui/src/app/pages/testrun/testrun.store.spec.ts
  modules/ui/src/app/pages/testrun/testrun.store.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
  modules/ui/src/app/store/state.ts
Labels: ui

#599 Update download Zip file modal
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.scss
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts
  modules/ui/src/app/pages/testrun/testrun.component.html
Labels: ui

#600 351338001: (feat) update rule for the third step message
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
Labels: ui

#604 347009372: (feat) add selector for profile options for GA4
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
Labels: ui

#603 Inform about a new network adapter
  modules/ui/angular.json
  modules/ui/package-lock.json
  modules/ui/package.json
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.module.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/mocks/settings.mock.ts
  modules/ui/src/app/model/setting.ts
  modules/ui/src/app/model/topic.ts
  modules/ui/src/app/pages/settings/settings.store.spec.ts
  modules/ui/src/app/pages/settings/settings.store.ts
  modules/ui/src/app/services/test-run-mqtt.service.spec.ts
  modules/ui/src/app/services/test-run-mqtt.service.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
  modules/ui/src/app/store/state.ts
Labels: ui

#606 The validation for duplicated name doesn't work for copied risk profile; The tooltips are not shown for action icons of the risk profile
  modules/ui/src/app/mocks/profile.mock.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: bug, ui

#607 346999760: (feat) [GA4] Track CA Certificates
  modules/ui/src/app/pages/certificates/certificates.store.spec.ts
  modules/ui/src/app/pages/certificates/certificates.store.ts
Labels: ui

#612 If profile is editing, return focus on profile
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: bug, ui

#610 Change title for save profile dialog according to type of profile
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: bug, ui

#613 The Download PDF button is enabled for the latest test run on the Testing page if the report was deleted on the Reports page
  modules/ui/src/app/pages/reports/reports.component.spec.ts
  modules/ui/src/app/pages/reports/reports.component.ts
  modules/ui/src/app/pages/reports/reports.store.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
Labels: bug, ui

#614 Show tooltip only on keyboard or hover
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
Labels: bug, ui

#619 Expired profile profile
  modules/ui/src/app/mocks/profile.mock.ts
  modules/ui/src/app/model/profile.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#622 Use device mac_addr if report mac_addr is missing
  modules/ui/src/app/mocks/reports.mock.ts
  modules/ui/src/app/model/testrun-status.ts
  modules/ui/src/app/pages/reports/reports.component.spec.ts
  modules/ui/src/app/pages/reports/reports.component.ts
  modules/ui/src/app/pages/reports/reports.store.spec.ts
  modules/ui/src/app/pages/reports/reports.store.ts
Labels: bug, ui

#625 Fix weasyprint/pydyf dependency mismatch that causes an API runtime error (too many arguments passed to pydif function by weasyprint)
  framework/requirements.txt
  make/DEBIAN/control
Labels: bug

#635 Adds close button for expired profile
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
Labels: bug, ui

#631 Copy changes from hotfix 1.3.1 to dev
  .github/workflows/scorecard.yml
  modules/test/tls/python/requirements.txt
Labels: dependencies

#638 Adds tooltip
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
Labels: bug

#640 Fix focus after profile delete - track by name
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: bug, ui

#643 Update the requests dependency
  framework/requirements.txt
  modules/test/tls/python/requirements.txt
Labels: dependencies

#645 Revert "Expired profile (#619)"
  modules/ui/src/app/mocks/profile.mock.ts
  modules/ui/src/app/model/profile.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#639 Improve documentation
  README.md
  docs/README.md
  docs/dev/README.md
  docs/dev/code_quality.md
  docs/network/README.md
  docs/network/add_new_service.md
  docs/test/README.md
  docs/test/modules.md
  modules/test/base/README.md
  modules/test/dns/README.md
  modules/test/dns/conf/module_config.json
Labels: docs
