Repository google/testrun, pull requests merged in 2024-08, with the labels that each got.

#650 Change tooltip
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
Labels: bug, ui

#656 Change tooltip for internet icon
  framework/python/src/net_orc/ip_control.py
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/components/wifi/wifi.component.html
  modules/ui/src/app/components/wifi/wifi.component.scss
  modules/ui/src/app/components/wifi/wifi.component.spec.ts
  modules/ui/src/app/components/wifi/wifi.component.ts
Labels: ui

#654 Feature/risk in selected
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.scss
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts
Labels: ui

#644 Use mqtt service instead of calling GET /status every 5 seconds.
  framework/python/src/common/session.py
  modules/ui/src/app/model/topic.ts
  modules/ui/src/app/services/test-run-mqtt.service.spec.ts
  modules/ui/src/app/services/test-run-mqtt.service.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
Labels: ui

#661 Adds test statuses
  modules/ui/src/app/model/testrun-status.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#660 Ignore folders in the root_certs folder
  framework/python/src/common/session.py
Labels: bug

#608 Allow ICMP response to DHCP messages in DHCP snooping test
  .gitignore
  modules/test/base/bin/setup
  modules/test/base/bin/start
  modules/test/base/bin/start_module
  modules/test/baseline/baseline.Dockerfile
  modules/test/conn/conn.Dockerfile
  modules/test/conn/python/src/connection_module.py
  modules/test/dns/dns.Dockerfile
  modules/test/ntp/ntp.Dockerfile
  modules/test/protocol/protocol.Dockerfile
  modules/test/services/services.Dockerfile
  testing/unit/conn/captures/monitor.pcap
  testing/unit/conn/captures/startup.pcap
  testing/unit/conn/conn_module_test.py
  testing/unit/run.sh
  testing/unit/tls/certs/_.google.com.crt
Labels: bug

#664 The risk profile saved with old format is shown improperly while loading based on a new format
  modules/ui/src/app/mocks/profile.mock.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
Labels: bug, ui

#662 GAR : The alt text for the expired risk profile should be communicated on Enter key
  modules/ui/src/app/mocks/profile.mock.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.ts
Labels: bug, ui

#677 Update internet connection when device is In Progress, Monitoring, Waiting for Device status
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
  modules/ui/src/app/store/state.ts
Labels: bug, ui

#670 Adds qualification form and creates first step
  modules/ui/src/app/components/stepper/stepper.component.html
  modules/ui/src/app/components/stepper/stepper.component.scss
  modules/ui/src/app/components/stepper/stepper.component.spec.ts
  modules/ui/src/app/components/stepper/stepper.component.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
  modules/ui/src/assets/icons/create_device_header.svg
Labels: ui

#680 Show error message if provided; show default message if no
  modules/ui/src/app/interceptors/error.interceptor.spec.ts
  modules/ui/src/app/interceptors/error.interceptor.ts
Labels: bug, ui

#681 Step 3 qualification process
  modules/ui/src/app/components/stepper/stepper-test.component.html
  modules/ui/src/app/components/stepper/stepper.component.html
  modules/ui/src/app/components/stepper/stepper.component.spec.ts
  modules/ui/src/app/components/stepper/stepper.component.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
Labels: ui

#669 Fix a delay in the internet connectivity check
  framework/python/src/common/tasks.py
  framework/python/src/common/util.py
  framework/python/src/net_orc/ip_control.py
  framework/python/src/net_orc/network_orchestrator.py
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
  modules/ui/src/app/store/state.ts
Labels: bug

#689 Device profile summary
  modules/ui/src/app/components/stepper/stepper.component.html
  modules/ui/src/app/components/stepper/stepper.component.scss
  modules/ui/src/app/components/stepper/stepper.component.ts
  modules/ui/src/app/pages/devices/components/device-form/device-form.component.spec.ts
  modules/ui/src/app/pages/devices/components/device-form/device-form.component.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
  modules/ui/src/app/pages/devices/devices.component.html
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
Labels: ui

#694 356882947: (feat) add pilot program section to welcome modal
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/components/callout/callout.component.html
  modules/ui/src/app/components/callout/callout.component.ts
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.scss
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.spec.ts
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.ts
  modules/ui/src/app/components/version/version.component.ts
  modules/ui/src/app/model/callout-type.ts
  modules/ui/src/app/model/version.ts
Labels: ui

#695 Update axios
  modules/ui/package-lock.json
Labels: dependencies

#693 Display outdated device Banner
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/components/callout/callout.component.html
  modules/ui/src/app/components/callout/callout.component.scss
  modules/ui/src/app/components/callout/callout.component.spec.ts
  modules/ui/src/app/components/callout/callout.component.ts
  modules/ui/src/app/components/device-item/device-item.component.spec.ts
  modules/ui/src/app/mocks/device.mock.ts
  modules/ui/src/app/mocks/reports.mock.ts
  modules/ui/src/app/mocks/testrun.mock.ts
  modules/ui/src/app/model/device.ts
  modules/ui/src/app/pages/devices/components/device-form/device-form.component.spec.ts
  modules/ui/src/app/pages/devices/components/device-form/device-form.component.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts
  modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.spec.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
  modules/ui/src/app/store/state.ts
  modules/ui/src/index.html
Labels: ui

#696 Only closeable banner should have close button
  modules/ui/src/app/components/callout/callout.component.html
Labels: bug, ui

#711 Display details of Device profile summary
  .github/workflows/testing.yml
  modules/ui/angular.json
  modules/ui/package-lock.json
  modules/ui/package.json
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.scss
  modules/ui/src/app/components/callout/callout.component.scss
  modules/ui/src/app/components/device-item/device-item.component.html
  modules/ui/src/app/components/device-item/device-item.component.scss
  modules/ui/src/app/components/device-item/device-item.component.spec.ts
  modules/ui/src/app/components/device-item/device-item.component.ts
  modules/ui/src/app/components/dynamic-form/dynamic-form.component.html
  modules/ui/src/app/components/dynamic-form/dynamic-form.component.scss
  modules/ui/src/app/components/pilot-icon/pilot-icon.component.ts
  modules/ui/src/app/components/qualification-icon/qualification-icon.component.ts
  modules/ui/src/app/components/spinner/spinner.component.scss
  modules/ui/src/app/components/stepper/stepper.component.ts
  modules/ui/src/app/components/version/version.component.spec.ts
  modules/ui/src/app/components/version/version.component.ts
  modules/ui/src/app/mocks/device.mock.ts
  modules/ui/src/app/model/device.ts
  modules/ui/src/app/model/profile.ts
  modules/ui/src/app/pages/certificates/certificate.validator.ts
  modules/ui/src/app/pages/devices/components/device-form/device-form.component.html
  modules/ui/src/app/pages/devices/components/device-form/device-form.component.scss
  modules/ui/src/app/pages/devices/components/device-form/device-form.component.spec.ts
  modules/ui/src/app/pages/devices/components/device-form/device-form.component.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
  modules/ui/src/app/pages/devices/devices.module.ts
  modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.scss
  modules/ui/src/app/pages/reports/reports.component.html
  modules/ui/src/app/pages/reports/reports.component.scss
  modules/ui/src/app/pages/settings/settings.component.ts
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.scss
  modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.html
  modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.scss
  modules/ui/src/app/pages/testrun/testrun.component.html
  modules/ui/src/app/pages/testrun/testrun.component.scss
  modules/ui/src/styles.scss
  modules/ui/src/theming/theme.scss
Labels: ui

#712 Test modules are not visible when screen is magnified or in mobile view
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
Labels: bug, ui

#713 360106064: (feat) display outdated device profiles
  modules/ui/src/app/components/device-item/device-item.component.html
  modules/ui/src/app/components/device-item/device-item.component.scss
  modules/ui/src/app/components/device-item/device-item.component.spec.ts
  modules/ui/src/app/components/device-item/device-item.component.ts
  modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.html
  modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.ts
  modules/ui/src/app/pages/testrun/testrun.component.html
  modules/ui/src/app/pages/testrun/testrun.component.spec.ts
  modules/ui/src/app/pages/testrun/testrun.store.spec.ts
  modules/ui/src/app/pages/testrun/testrun.store.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
  modules/ui/src/app/store/state.ts
  modules/ui/src/theming/colors.scss
Labels: ui

#715 Aria labels for stepper and Go to next step button are incorrect
  modules/ui/src/app/components/stepper/stepper.component.html
  modules/ui/src/app/components/stepper/stepper.component.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
Labels: bug, ui

#718 Overlapping of error messages in Device menu
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
Labels: bug, ui

#719 Confirmation of closing is displayed when no changes made in Device menu
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
Labels: bug, ui

#720 Fix overflow; fix hint on small form width
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
Labels: bug, ui

#725 Fix display of risk profile
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
Labels: bug, ui

#724 Save Device profile with new questions
  modules/ui/angular.json
  modules/ui/src/app/components/stepper/stepper.component.scss
  modules/ui/src/app/components/stepper/stepper.component.ts
  modules/ui/src/app/model/device.ts
  modules/ui/src/app/pages/devices/components/device-form/device.validators.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
  modules/ui/src/index.html
Labels: ui

#721 Change response of device config steps to match UI expectations
  framework/python/src/api/api.py
Labels: bug

#726 362470780: (fix) change for preventing callouts overlapping
  modules/ui/src/styles.scss
Labels: bug, ui

#728 362921863: (fix) create device popup view in firefox
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
  modules/ui/src/styles.scss
  modules/ui/src/theming/variables.scss
Labels: bug, ui

#733 362924178: (fix) change to align information on the welcome modal
  modules/ui/src/app/components/callout/callout.component.html
  modules/ui/src/app/components/callout/callout.component.scss
Labels: bug, ui

#734 Fix UI issues
  modules/ui/src/app/components/device-item/device-item.component.scss
  modules/ui/src/app/mocks/device.mock.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
  modules/ui/src/app/pages/devices/devices.component.html
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
  modules/ui/src/styles.scss
  modules/ui/src/theming/theme.scss
  modules/ui/src/theming/variables.scss
Labels: bug, ui

#735 363180408: (fix) change callouts show start testrun if no valid device is available
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/styles.scss
Labels: bug, ui

#730 Remove default values from config for network adapters
  framework/python/src/api/api.py
  local/system.json.example
Labels: bug

#727 Icons are not present on device tile
  modules/ui/src/app/components/device-item/device-item.component.html
Labels: bug, ui
