Repository google/testrun, pull requests merged in 2024-04, with the labels that each got.

#372 Fix bug with deleting reports
  framework/python/src/common/device.py
  framework/python/src/core/testrun.py
Labels: bug

#373 Add a SYN/ACK filter to unencrypted TLS check
  modules/test/tls/python/src/tls_util.py
Labels: bug

#382 Add test status documentation
  docs/get_started.md
  docs/test/index.md
  docs/test/statuses.md
Labels: docs, request

#367 330867613: (feat) change start testrun icon on device tile
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/components/device-item/device-item.component.html
  modules/ui/src/app/components/device-item/device-item.component.scss
  modules/ui/src/assets/icons/device_run.svg
  modules/ui/src/styles.scss
Labels: ui

#362 331378849: (feat) add log level explanation
  modules/ui/src/app/mocks/settings.mock.ts
  modules/ui/src/app/pages/settings/settings.store.spec.ts
  modules/ui/src/app/pages/settings/settings.store.ts
Labels: ui

#375 Extend timeout when testrun is stopping
  modules/ui/src/app/interceptors/error.interceptor.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: bug, ui

#306 Adds version analytics event
  modules/ui/src/app/components/version/version.component.spec.ts
  modules/ui/src/app/components/version/version.component.ts
Labels: ui

#392 Adds testrun component state
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.html
  modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.spec.ts
  modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.ts
  modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.html
  modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.spec.ts
  modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.ts
  modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.html
  modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.spec.ts
  modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.ts
  modules/ui/src/app/pages/testrun/progress.component.html
  modules/ui/src/app/pages/testrun/progress.component.spec.ts
  modules/ui/src/app/pages/testrun/progress.component.ts
  modules/ui/src/app/pages/testrun/testrun.store.spec.ts
  modules/ui/src/app/pages/testrun/testrun.store.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
  modules/ui/src/app/store/state.ts
Labels: ui

#395 Upgrade dependencies in TLS module
  modules/test/tls/python/requirements.txt
Labels: dependencies

#399 332883321: (feat) add support for Feature Not Present and Error statuses
  modules/ui/src/app/model/testrun-status.ts
  modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.spec.ts
  modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#406 333723882: (feat) add download options on testing page
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.html
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.scss
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.spec.ts
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.ts
  modules/ui/src/app/pages/testrun/progress.component.html
  modules/ui/src/app/pages/testrun/progress.component.spec.ts
  modules/ui/src/app/pages/testrun/progress.module.ts
Labels: ui

#405 Fix scrolls for mozilla
  modules/ui/src/app/app.component.scss
  modules/ui/src/app/pages/reports/history.component.scss
  modules/ui/src/styles.scss
Labels: bug, ui

#410 333725552: (feat) ability to shutdown testrun
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.module.ts
  modules/ui/src/app/components/shutdown-app-modal/shutdown-app-modal.component.html
  modules/ui/src/app/components/shutdown-app-modal/shutdown-app-modal.component.scss
  modules/ui/src/app/components/shutdown-app-modal/shutdown-app-modal.component.spec.ts
  modules/ui/src/app/components/shutdown-app-modal/shutdown-app-modal.component.ts
  modules/ui/src/app/components/shutdown-app/shutdown-app.component.html
  modules/ui/src/app/components/shutdown-app/shutdown-app.component.scss
  modules/ui/src/app/components/shutdown-app/shutdown-app.component.spec.ts
  modules/ui/src/app/components/shutdown-app/shutdown-app.component.ts
  modules/ui/src/app/providers/window.provider.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
  modules/ui/src/theming/colors.scss
Labels: ui

#416 336737453: (fix) the reports table is not fitting the content
  modules/ui/src/app/pages/reports/history.component.scss
Labels: bug, ui

#415 Adds ga to track testrun initiation
  modules/ui/src/app/pages/testrun/progress.component.spec.ts
  modules/ui/src/app/pages/testrun/progress.component.ts
Labels: bug, ui

#419 336268076: (fix) change borders for the button and options in download dropdown
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.html
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.scss
Labels: bug, ui

#403 Fix mac_address validation
  modules/ui/src/app/pages/devices/device-repository.component.html
  modules/ui/src/app/pages/devices/device-repository.component.spec.ts
Labels: bug, ui

#421 Fix function return value
  modules/ui/src/app/pages/testrun/progress.component.ts
Labels: bug, ui

#420 Fix redirect + adds google analytics
  modules/ui/src/app/pages/devices/device-repository.component.spec.ts
  modules/ui/src/app/pages/devices/device-repository.component.ts
Labels: bug, ui

#417 Change model and manufacturer length
  modules/ui/src/app/pages/devices/components/device-form/device-form.component.html
  modules/ui/src/app/pages/devices/components/device-form/device-form.component.spec.ts
  modules/ui/src/app/pages/devices/components/device-form/device.validators.ts
  modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.ts
  modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.ts
Labels: bug, ui

#404 In progress test result
  modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.html
  modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.spec.ts
Labels: bug, ui

#383 Fixes defects in the PDF report if a long device name is specified
  framework/python/src/api/api.py
  framework/python/src/common/testreport.py
Labels: bug
