Repository google/testrun, pull requests merged in 2024-09, with the labels that each got.

#736 Adds delete device button
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
Labels: ui

#737 Fix device testing type
  modules/ui/src/app/model/device.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
Labels: bug, ui

#738 Check is value is null, undefined or empty string
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
Labels: bug, ui

#739 362724933: (feat) add program type to results tab
  modules/ui/src/app/mocks/reports.mock.ts
  modules/ui/src/app/model/testrun-status.ts
  modules/ui/src/app/pages/reports/reports.component.html
  modules/ui/src/app/pages/reports/reports.store.spec.ts
  modules/ui/src/app/pages/reports/reports.store.ts
Labels: ui

#741 Fix design issues
  modules/ui/src/app/components/stepper/stepper.component.scss
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
  modules/ui/src/theming/variables.scss
Labels: bug, ui

#745 362646053: (feat) add program icons and change borders in tiles
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/components/callout/callout.component.html
  modules/ui/src/app/components/callout/callout.component.scss
  modules/ui/src/app/components/callout/callout.component.spec.ts
  modules/ui/src/app/components/callout/callout.component.ts
  modules/ui/src/app/components/device-item/device-item.component.html
  modules/ui/src/app/components/device-item/device-item.component.scss
  modules/ui/src/app/components/device-item/device-item.component.spec.ts
  modules/ui/src/app/components/device-item/device-item.component.ts
  modules/ui/src/app/components/pilot-icon/pilot-icon.component.ts
  modules/ui/src/app/components/program-type-icon/program-type-con.component.spec.ts
  modules/ui/src/app/components/program-type-icon/program-type-icon.component.ts
  modules/ui/src/app/components/qualification-icon/qualification-icon.component.ts
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.spec.ts
  modules/ui/src/app/components/version/version.component.spec.ts
  modules/ui/src/app/model/program-type.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
  modules/ui/src/assets/icons/pilot.svg
  modules/ui/src/assets/icons/qualification.svg
Labels: ui

#746 Adds dialog if profile is successfully saved
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.html
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.scss
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
Labels: ui

#748 364545807: (fix) changes to prevent the second callout is hidden
  modules/ui/src/app/app.component.html
  modules/ui/src/app/components/callout/callout.component.html
  modules/ui/src/app/components/callout/callout.component.scss
  modules/ui/src/app/components/callout/callout.component.ts
  modules/ui/src/styles.scss
Labels: bug, ui

#749 Scroll is not displayed when to zoom the page with opened modal
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
Labels: bug, ui

#752 364828484: (fix) [GAR 1.1] change program icon aria-label
  modules/ui/src/app/components/device-item/device-item.component.html
  modules/ui/src/app/components/device-item/device-item.component.ts
Labels: bug, ui

#757 364578734: (fix) change device tile view to meet size
  modules/ui/src/app/components/device-item/device-item.component.scss
Labels: bug, ui

#758 Delete and Cancel buttons have different background colors on hover
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
Labels: bug, ui

#760 365059335: (fix) [GAR 1.1] change device tile structure to allow read by Orca screen reader
  modules/ui/src/app/components/device-item/device-item.component.html
  modules/ui/src/app/components/device-item/device-item.component.scss
  modules/ui/src/app/components/device-item/device-item.component.spec.ts
  modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.spec.ts
Labels: bug, ui

#759 Change hostname for MQTT service
  modules/ui/src/app/app.module.ts
Labels: ui

#755 Update cryptography dependency
  modules/test/tls/python/requirements.txt
Labels: dependencies, python

#761 No update from BE of test status results during testrun
  modules/ui/src/app/app.module.ts
  modules/ui/src/app/components/callout/callout.component.scss
  modules/ui/src/app/store/effects.ts
Labels: bug, ui

#762 In High risk profile pop-up text is the same as in Limited risk
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.html
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.ts
Labels: bug, ui

#754 Focus disappears upon saving device profile in Edit modal
  modules/ui/src/app/pages/devices/devices.component.html
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
Labels: bug, ui

#763 The focus is not set to the first interactive element after clicking the "Risk assessment questionnaire"link on the callout
  modules/ui/src/app/app.component.ts
Labels: bug, ui

#765 The callouts are merged visually if zooming in is 175% and more
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.module.ts
  modules/ui/src/app/components/callout/callout.component.scss
  modules/ui/src/app/components/callout/dynamic-top.directive.ts
Labels: bug, ui

#770 362959152: (feat) add testing complete modal
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.module.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/components/download-report/download-report.component.scss
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.scss
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts
  modules/ui/src/app/components/testing-complete/testing-complete.component.spec.ts
  modules/ui/src/app/components/testing-complete/testing-complete.component.ts
  modules/ui/src/app/model/testrun-status.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/effects.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
  modules/ui/src/app/store/state.ts
Labels: ui

#769 The callouts are merged visually if zooming in is 175% and more
  modules/ui/src/app/components/callout/dynamic-top.directive.ts
Labels: bug, ui

#772 The callout/banner is shown improperly
  modules/ui/src/app/components/callout/dynamic-top.directive.ts
  modules/ui/src/styles.scss
Labels: bug, ui

#775 Rename Program column on Reports tab
  modules/ui/src/app/pages/reports/reports.component.html
Labels: bug, ui

#773 Hide "Create" text in edit mode
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts
Labels: bug, ui

#777 The link to validation error on the final summary device page opens the Cancel dialog
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
Labels: bug, ui

#779 Update Risk profile result modal logic
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.html
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: ui

#778 Filter Not Started tests from test count
  modules/ui/src/app/mocks/testrun.mock.ts
  modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.spec.ts
  modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.ts
Labels: bug, ui

#780 Change version label
  modules/ui/package-lock.json
  modules/ui/src/app/components/version/version.component.html
  modules/ui/src/app/components/version/version.component.spec.ts
  modules/ui/src/app/components/version/version.component.ts
Labels: bug, ui

#781 Display tags for Testrun progress page
  modules/ui/src/app/mocks/reports.mock.ts
  modules/ui/src/app/mocks/testrun.mock.ts
  modules/ui/src/app/model/testrun-status.ts
  modules/ui/src/app/pages/testrun/testrun.component.html
  modules/ui/src/app/pages/testrun/testrun.component.scss
  modules/ui/src/app/pages/testrun/testrun.component.spec.ts
  modules/ui/src/app/pages/testrun/testrun.module.ts
  modules/ui/src/styles.scss
Labels: ui

#782 365728028: (feat) improve callouts
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.scss
  modules/ui/src/app/app.module.ts
  modules/ui/src/app/components/callout/callout.component.scss
  modules/ui/src/app/components/callout/dynamic-top.directive.ts
  modules/ui/src/app/pages/devices/devices.component.scss
  modules/ui/src/app/pages/reports/reports.component.scss
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss
  modules/ui/src/app/pages/testrun/testrun.component.scss
  modules/ui/src/styles.scss
Labels: ui

#785 367673910: (fix) prevent download PDF report button focused twice on completed testing modal
  modules/ui/src/app/components/download-report/download-report.component.html
  modules/ui/src/app/components/download-report/download-report.component.ts
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
Labels: bug, ui

#786 Fix tags
  modules/ui/src/app/model/testrun-status.ts
  modules/ui/src/app/pages/testrun/testrun.component.html
Labels: bug, ui

#784 Console errors on starting the test attempt
  modules/ui/package-lock.json
  modules/ui/package.json
  modules/ui/src/app/components/download-report/download-report.component.ts
  modules/ui/src/app/components/report-action/report-action.component.ts
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.ts
  modules/ui/src/app/pages/testrun/testrun.component.html
  modules/ui/src/app/pages/testrun/testrun.component.ts
Labels: bug, ui

#788 Destroy "waiting for device" snackbar when status changed
  modules/ui/src/app/store/effects.ts
Labels: bug, ui

#789 The focus on the specific answer in the risk profile is counted as updating data and activates the Discard button
  modules/ui/src/app/components/dynamic-form/dynamic-form.component.ts
Labels: bug, ui

#794 The focus is not visible after the Complete testing modal is closed.
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
  modules/ui/src/app/components/testing-complete/testing-complete.component.ts
Labels: bug, ui

#790 The focused risk profile is not communicated by screen reader after saving it on the list
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: bug, ui

#799 The confirmation dialogto save changes appears for the Risk profile without changes made.
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: bug, ui

#800 Risk profile completed modal: the redundant information is communicated by Screen reader
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: bug, ui

#802 New Risk Assessment button is not announced after removing all Risk Profiles
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
Labels: bug, ui

#807 369106935: (fix) [a11y] make focused element announced
  modules/ui/src/app/components/testing-complete/testing-complete.component.ts
Labels: bug, ui

#808 The focused risk profile is not communicated by screen reader after saving it on the list
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: bug, ui

#806 The focus is not moved to the callout about risk profile questionnaire while running the test attempt
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.ts
Labels: bug, ui

#812 369314564: (fix) set focus after callout dismissed
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
Labels: bug, ui

#813 369312866: (fix) set focus after welcome modal is closed
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.spec.ts
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.ts
Labels: bug, ui

#810 Fix profiles page style to fit the screen
  modules/ui/src/styles.scss
Labels: bug, ui

#815 358071738: (feat) prevent listening mgtt internet connect event in single port mode
  modules/ui/src/app/model/setting.ts
  modules/ui/src/app/store/effects.ts
Labels: ui

#816 Fix condition to show dialog on name change
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: bug, ui

#801 365978129: (feat) add PDF report templates
  resources/report/pilot-icon.png
  resources/report/pilot-report-example.html
  resources/report/qualification-icon.png
  resources/report/qualification-report-example.html
  resources/report/risk_report_styles.css
  resources/report/risk_report_template.html
  resources/report/test_report_styles.css
  resources/report/test_report_template_new.html
Labels: ui

#818 369538601: (fix) set focus to first interactive elem after stop test attempt
  modules/ui/src/app/pages/testrun/testrun.component.ts
Labels: bug, ui

#817 Remove steps to resolve from informational tests
  framework/python/src/common/session.py
Labels: bug

#819 369327155: (fix) set focus to selected risk profile if no changes on edit
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: bug, ui

#822 The focus is not returned to the previous element after closing the snackbar about new port availability
  modules/ui/src/app/services/notification.service.ts
Labels: bug, ui

#825 Delete icon is implemented as a link and does not react to Space button
  modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.html
Labels: bug, ui

#826 369779748: (fix) add field name to validation rule for announce by Screen Reader
  modules/ui/src/app/components/dynamic-form/dynamic-form.component.html
Labels: bug, ui

#829 367979183: (fix) announce the result and description on completed test modal
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
Labels: bug, ui

#832 369542969: (fix) announce completed test modal
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
  modules/ui/src/app/components/testing-complete/testing-complete.component.spec.ts
  modules/ui/src/app/components/testing-complete/testing-complete.component.ts
Labels: bug, ui
