Repository google/testrun, pull requests merged in 2024-10, with the labels that each got.

#837 369538601: (fix) focus first interactive elem on start or stop testrun
  modules/ui/src/app/pages/testrun/testrun.component.spec.ts
  modules/ui/src/app/pages/testrun/testrun.component.ts
  modules/ui/src/app/services/notification.service.ts
Labels: bug, ui

#842 369788198: (fix) validation message alignment on create device
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
Labels: bug, ui

#843 370729271: (fix) remove asterisks on the questions in the device flow
  modules/ui/src/app/components/dynamic-form/dynamic-form.component.html
  modules/ui/src/app/components/dynamic-form/dynamic-form.component.spec.ts
Labels: bug, ui

#844 370711565: (fix) changes for informational test result
  modules/ui/src/app/model/testrun-status.ts
  modules/ui/src/app/pages/reports/reports.component.spec.ts
  modules/ui/src/app/pages/reports/reportscomponent.ts
  modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.spec.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
  modules/ui/src/styles.scss
  resources/report/test_report_styles.css
Labels: bug, ui

#845 Add role and aria-live for screen reader
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
Labels: bug, ui

#847 370923173: (fix) remove close button from the certificates panel
  modules/ui/src/app/pages/certificates/certificates.component.html
  modules/ui/src/app/pages/certificates/certificates.component.spec.ts
  modules/ui/src/app/pages/certificates/certificates.component.ts
Labels: bug, ui

#849 Change text in risk dialog
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.html
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.ts
Labels: bug, ui

#850 370012527: (feat) update PDF reports styles
  framework/python/src/test_orc/test_orchestrator.py
  resources/report/device_qualification_report_example.html
  resources/report/header_macros.jinja
  resources/report/pilot_report_example.html
  resources/report/test_report_styles.css
  resources/report/test_report_template.html
Labels: ui

#852 369538601: (fix) set focus to first interactive elem after stop test attempt
  modules/ui/src/app/pages/testrun/testrun.component.ts
Labels: bug, ui

#853 371506031: (fix) make the welcome modal be on top completed test modal
  modules/ui/src/app/components/version/version.component.spec.ts
  modules/ui/src/app/components/version/version.component.ts
Labels: bug, ui

#851 366151318: (fix) add communicate steps on create device
  modules/ui/src/app/components/device-item/device-item.component.scss
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
  modules/ui/src/styles.scss
Labels: bug, ui

#856 370941517: (fix) return focus to initial btn after cancel download zip
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
Labels: bug, ui

#858 371177676: (fix) set focus to the initial device if cancel on edit device
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
Labels: bug, ui

#863 371525395: (fix) exclude error status from count of completed test result
  modules/ui/src/app/mocks/testrun.mock.ts
  modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.spec.ts
  modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.ts
Labels: bug, ui

#864 371948760: (fix) set focus to first interactive elem after start testrun from device
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
Labels: bug, ui

#873 372610099: (fix) update the text for Risk assessment complete modal
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.html
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.ts
Labels: bug, ui

#883 Remove global app component store
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
  modules/ui/src/app/store/state.ts
Labels: ui

#882 372804973: (fix) make risk profile names not case sensitive
  modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
Labels: bug, ui

#874 370942396: (fix) change create device errors and program styles to improve view in the helperbird
  modules/ui/src/app/components/program-type-icon/program-type-icon.component.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
Labels: bug, ui

#886 Modify download zip modal
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts
  modules/ui/src/app/components/testing-complete/testing-complete.component.spec.ts
  modules/ui/src/app/components/testing-complete/testing-complete.component.ts
Labels: ui

#887 369806347: (fix) improve unit tests
  modules/ui/src/app/components/download-report/download-report.component.spec.ts
  modules/ui/src/app/components/report-action/report-action.component.spec.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts
  modules/ui/src/app/pages/reports/components/filter-chips/filter-chips.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts
  modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.spec.ts
  modules/ui/src/app/services/notification.service.spec.ts
Labels: ui

#888 [GA4] Track Pilot assessment results
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
Labels: ui

#889 373617780: (fix) change to allow MAC address error text move on to next line
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
Labels: bug, ui

#895 373855404: (fix) allow to change case of letters for existing profile name
  modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
Labels: bug, ui

#897 374248446: Remove v from firmware version in UI
  modules/ui/src/app/pages/testrun/testrun.component.ts
Labels: request

#899 372768360: (feat) [Settings] only device port is enabled in no internet mode
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/mocks/settings.mock.ts
  modules/ui/src/app/pages/settings/components/settings-dropdown/settings-dropdown.component.scss
  modules/ui/src/app/pages/settings/settings.component.html
  modules/ui/src/app/pages/settings/settings.component.spec.ts
  modules/ui/src/app/pages/settings/settings.component.ts
  modules/ui/src/app/pages/settings/settings.store.spec.ts
  modules/ui/src/app/pages/settings/settings.store.ts
Labels: ui

#906 The Complete testing modal is shown with Idle result if the app is reopened in another tab
  modules/ui/src/app/components/testing-complete/testing-complete.component.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
Labels: bug, ui

#909 374055268: (fix) prevent overwrite copied profile
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: bug, ui

#903 Update dependencies
  framework/requirements.txt
  modules/ui/package-lock.json
  modules/ws/ws.Dockerfile
Labels: dependencies

#915 The "No ports" callout blinks on loading the page
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
Labels: bug, ui

#917 374258745: (fix) [PDF report] wrap long words into the next line to prevent cutting content
  resources/report/test_report_styles.css
Labels: bug

#918 The answers to questions in the Device popup are not displayed
  modules/ui/src/app/components/dynamic-form/dynamic-form.component.html
  modules/ui/src/app/components/dynamic-form/dynamic-form.component.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
Labels: bug, ui

#896 374084009: Fix error on restoring DHCP server configuration if device has no DHCP lease
  modules/network/dhcp-1/python/src/grpc_server/dhcp_leases.py
  modules/network/dhcp-2/python/src/grpc_server/dhcp_leases.py
  modules/network/radius/bin/start_network_service
  modules/test/base/python/src/test_module.py
  modules/test/baseline/bin/start_test_module
  modules/test/conn/bin/start_test_module
  modules/test/conn/conf/module_config.json
  modules/test/conn/python/src/connection_module.py
  modules/test/conn/python/src/dhcp_util.py
  modules/test/dns/bin/start_test_module
  modules/test/dns/python/src/dns_module.py
  modules/test/ntp/bin/start_test_module
  modules/test/ntp/python/src/ntp_module.py
  modules/test/protocol/bin/start_test_module
  modules/test/protocol/python/src/protocol_module.py
  modules/test/protocol/python/src/run.py
  modules/test/services/bin/start_test_module
  modules/test/services/python/src/services_module.py
  modules/test/tls/bin/start_test_module
  modules/test/tls/python/src/tls_module.py
  testing/unit/conn/conn_module_test.py
  testing/unit/dns/dns_module_test.py
  testing/unit/ntp/ntp_module_test.py
  testing/unit/report/report_compliant.json
  testing/unit/report/report_noncompliant.json
  testing/unit/services/services_module_test.py
  testing/unit/tls/tls_module_test.py
Labels: bug
