Repository google/testrun, pull requests merged in 2024-06, with the labels that each got.

#490 Update consent form
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.scss
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.spec.ts
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.ts
Labels: ui

#493 The state of the system settings panel is not communicated in the screen reader
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
Labels: bug, ui

#491 Set response code if failed cert upload
  framework/python/src/api/api.py
Labels: bug

#492 342365574: (feat) display info about Risk Assessment during testing
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/components/callout/callout.component.scss
  modules/ui/src/app/model/callout-type.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
  modules/ui/src/app/store/reducers.spec.ts
  modules/ui/src/app/store/reducers.ts
  modules/ui/src/app/store/selectors.spec.ts
  modules/ui/src/app/store/selectors.ts
  modules/ui/src/app/store/state.ts
  modules/ui/src/styles.scss
Labels: ui

#494 System status is not updated when test run is started
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
  modules/ui/src/app/pages/devices/devices.store.spec.ts
  modules/ui/src/app/pages/devices/devices.store.ts
  modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.html
  modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.spec.ts
  modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.ts
  modules/ui/src/app/pages/testrun/testrun.component.spec.ts
  modules/ui/src/app/pages/testrun/testrun.component.ts
  modules/ui/src/app/pages/testrun/testrun.store.spec.ts
  modules/ui/src/app/pages/testrun/testrun.store.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: bug, ui

#496 341966862: (feat) display info about risk assessment in welcome modal
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.scss
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.spec.ts
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.ts
  modules/ui/src/app/components/version/version.component.ts
  modules/ui/src/app/model/version.ts
Labels: ui

#497 Adds download zip window
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.html
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.scss
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.scss
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts
  modules/ui/src/app/pages/reports/reports.component.html
  modules/ui/src/app/pages/reports/reports.component.spec.ts
  modules/ui/src/app/pages/reports/reports.store.spec.ts
  modules/ui/src/app/pages/reports/reports.store.ts
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.html
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.scss
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.spec.ts
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.ts
  modules/ui/src/app/pages/testrun/testrun.component.html
  modules/ui/src/app/pages/testrun/testrun.component.spec.ts
  modules/ui/src/app/pages/testrun/testrun.store.spec.ts
  modules/ui/src/app/pages/testrun/testrun.store.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#500 344874424: (fix) disable device tile in Canceling status
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
Labels: bug, ui

#501 Fix/UI/345164706
  modules/ui/src/app/pages/testrun/testrun.component.html
  modules/ui/src/app/pages/testrun/testrun.component.spec.ts
Labels: bug, ui

#502 GA option issues on the Welcome modal
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
  modules/ui/src/index.html
Labels: bug, ui

#503 345202815: (fix) callout with the RA message is shown on the RA page
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.ts
Labels: bug, ui

#506 Announce disabled state of settings panel
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.component.spec.ts
  modules/ui/src/app/app.component.ts
Labels: bug, ui

#508 The Downlaod ZIP action can not be performed using the keaboard
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
  modules/ui/src/app/pages/reports/reports.component.html
  modules/ui/src/app/pages/reports/reports.component.scss
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.html
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.ts
Labels: bug, ui

#510 Add .cer and .crt for cert upload
  framework/python/src/api/api.py
Labels: bug

#514 340859666: (feat): display risk profile form with name field
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.module.ts
Labels: ui

#515 Generate Risk profile from json
  modules/ui/src/app/mocks/profile.mock.ts
  modules/ui/src/app/model/profile.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#517 The Downlaod ZIP action can not be performed using the keyboard
  framework/python/src/api/api.py
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
  modules/ui/src/app/pages/reports/reports.component.html
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: bug, ui

#524 Fix styles for helperbird
  modules/ui/src/app/app.component.scss
  modules/ui/src/app/components/device-item/device-item.component.scss
  modules/ui/src/app/components/shutdown-app/shutdown-app.component.scss
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.scss
  modules/ui/src/app/pages/certificates/certificates.component.scss
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
  modules/ui/src/app/pages/settings/settings.component.scss
  modules/ui/src/app/pages/testrun/components/download-options/download-options.component.scss
Labels: bug, ui

#523 Form from json validation
  modules/ui/src/app/mocks/profile.mock.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
  modules/ui/src/app/services/test-run.service.spec.ts
Labels: ui

#526 Fix vulnerabilities in dependencies
  modules/ui/package-lock.json
Labels: ui, dependencies

#530 The action buttons are shown in the improper state
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
Labels: bug, ui

#529 Mark fields required when trimmed value is empty
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
Labels: bug, ui

#525 Update requests library
  modules/test/tls/python/requirements.txt
Labels: dependencies

#531 Remove debug artifact
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
Labels: bug, ui

#532 Fix scroll area on reports page
  modules/ui/src/app/pages/reports/reports.component.scss
Labels: bug, ui

#536 Announce risk form open; focus first element in container
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: bug, ui

#538 Field validation issues
  modules/ui/src/app/mocks/profile.mock.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
Labels: bug, ui

#539 345258435: (feat) display expired certificate
  modules/ui/src/app/model/certificate.ts
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.html
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.scss
  modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.ts
Labels: ui

#540 348187954: (fix) update callouts position on the small window size
  modules/ui/src/app/components/callout/callout.component.scss
Labels: bug, ui

#541 348356236: (fix) add tooltips for icons without any accompanying text
  modules/ui/src/app/app.component.html
  modules/ui/src/app/app.module.ts
  modules/ui/src/app/components/device-item/device-item.component.html
  modules/ui/src/app/components/device-item/device-item.component.ts
  modules/ui/src/app/components/shutdown-app/shutdown-app.component.html
  modules/ui/src/app/components/shutdown-app/shutdown-app.component.ts
Labels: bug, ui

#542 348353479: (fix) add tooltip for the download zip button using the keyboard
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
  modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
Labels: bug, ui

#543 348361925: (fix) add helper text for mandatory profile name field
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
Labels: bug, ui

#533 Save new risk profile
  modules/ui/src/app/app.store.spec.ts
  modules/ui/src/app/app.store.ts
  modules/ui/src/app/mocks/profile.mock.ts
  modules/ui/src/app/model/profile.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
  modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.spec.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
  modules/ui/src/app/store/actions.ts
  modules/ui/src/app/store/effects.spec.ts
  modules/ui/src/app/store/effects.ts
Labels: ui

#544 Adds edit risk profile
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts
  modules/ui/src/app/components/simple-dialog/simple-dialog.component.html
  modules/ui/src/app/components/simple-dialog/simple-dialog.component.scss
  modules/ui/src/app/components/simple-dialog/simple-dialog.component.spec.ts
  modules/ui/src/app/components/simple-dialog/simple-dialog.component.ts
  modules/ui/src/app/mocks/profile.mock.ts
  modules/ui/src/app/model/profile.ts
  modules/ui/src/app/pages/certificates/certificates.component.spec.ts
  modules/ui/src/app/pages/certificates/certificates.component.ts
  modules/ui/src/app/pages/devices/devices.component.spec.ts
  modules/ui/src/app/pages/devices/devices.component.ts
  modules/ui/src/app/pages/devices/devices.module.ts
  modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.spec.ts
  modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
  modules/ui/src/app/pages/testrun/testrun.component.spec.ts
  modules/ui/src/app/pages/testrun/testrun.component.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#547 Fix autozise
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
Labels: bug, ui

#549 Adds save draft
  modules/ui/src/app/mocks/profile.mock.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
Labels: ui

#553 346351108: (feat) display risk assessment result
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.scss
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts
  modules/ui/src/app/model/profile.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
  modules/ui/src/styles.scss
  modules/ui/src/theming/colors.scss
Labels: ui

#554 Close form after selected risk profile was deleted
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: bug, ui

#555 Fix error when updating a profile
  framework/python/src/common/session.py
  local/risk_profiles/Primary profile.json
Labels: bug

#551 Render informational result correctly
  framework/python/src/common/testreport.py
Labels: bug

#550 Re-add method for attaching profile to ZIP export
  framework/python/src/common/risk_profile.py
Labels: bug

#548 Fix bug with version number if no internet connection is available
  framework/python/src/api/api.py
Labels: bug

#557 349769454: (fix) update size on the empty reports page to prevent overlapping
  modules/ui/src/app/pages/reports/reports.component.scss
Labels: bug, ui

#552 Changes the icon; adds create date
  modules/ui/src/app/app.component.ts
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
  modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.scss
  modules/ui/src/app/mocks/profile.mock.ts
  modules/ui/src/app/model/profile.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.ts
  modules/ui/src/assets/icons/draft.svg
Labels: bug, ui

#558 349783464: (fix) add styles for selected elements and fix form size on RA
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss
  modules/ui/src/theming/colors.scss
Labels: bug, ui

#559 349793005: (fix) change focus to profile form to scroll up on opening profile
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Labels: bug, ui

#560 The focus is not shown after the risk profile has been created
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
  modules/ui/src/app/services/focus-manager.service.ts
Labels: bug, ui
