Repository google/testrun, pull requests merged in 2025-01, with the labels that each got.

#1039 [GM3] The icon for warning callouts differs from the icons of other callouts
  modules/ui/src/app/components/callout/callout.component.html
  modules/ui/src/app/components/callout/callout.component.scss
  modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.scss
  modules/ui/src/app/model/callout-type.ts
  modules/ui/src/app/pages/general-settings/general-settings.component.html
  modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.html
Labels: ui

#1038 Update Cryptography and Jinja
  framework/requirements.txt
  modules/test/tls/python/requirements.txt
Labels: dependencies

#1040 386919467: (fix) make internet port disable in single mode after enable form
  modules/ui/src/app/pages/general-settings/general-settings.component.spec.ts
  modules/ui/src/app/pages/general-settings/general-settings.component.ts
  modules/ui/src/app/pages/general-settings/general-settings.store.ts
Labels: ui

#1042 387242682: (fix) make save button available on the settings page with callouts
  modules/ui/src/app/pages/general-settings/general-settings.component.scss
  modules/ui/src/styles.scss
  modules/ui/src/theming/variables.scss
Labels: ui

#1045 387242169: (fix) change availability of certificate page
  modules/ui/src/app/pages/certificates/certificates.component.scss
  modules/ui/src/app/pages/certificates/components/certificates-table/certificates-table.component.scss
  modules/ui/src/styles.scss
  modules/ui/src/theming/variables.scss
Labels: ui

#1048 Allow NTPv3 packets as long as NTPv4 is also present
  modules/test/ntp/python/src/ntp_module.py
Labels: test

#1051 387461943: (fix) remove double scroll on device page
  modules/ui/src/app/components/list-layout/list-layout.component.scss
Labels: ui

#1054 385169773: (feat) add devices input form
  modules/ui/src/app/components/list-layout/list-layout.component.html
  modules/ui/src/app/components/list-layout/list-layout.component.scss
  modules/ui/src/app/components/list-layout/list-layout.component.ts
  modules/ui/src/app/pages/devices/components/device-form/device.validators.ts
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
  modules/ui/src/app/pages/devices/devices.component.html
  modules/ui/src/app/pages/devices/devices.component.ts
Labels: ui

#1057 389661817: (feat) change profile name validation
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
  modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
Labels: ui

#1058 Rename Pilot test results
  modules/ui/src/app/mocks/testrun.mock.ts
  modules/ui/src/app/model/testrun-status.ts
  modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.html
  modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.spec.ts
  modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.ts
  modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.html
  modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.scss
  modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.spec.ts
  modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.ts
Labels: ui

#1062 389657377: (feat) add status Starting to UI
  modules/ui/src/app/mocks/testrun.mock.ts
  modules/ui/src/app/model/testrun-status.ts
  modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.ts
  modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.ts
  modules/ui/src/app/pages/testrun/testrun.store.spec.ts
  modules/ui/src/app/pages/testrun/testrun.store.ts
  modules/ui/src/app/services/test-run.service.spec.ts
  modules/ui/src/app/services/test-run.service.ts
Labels: ui

#1064 3 dots menu should be disabled for devices under test
  modules/ui/src/app/components/device-item/device-item.component.html
  modules/ui/src/app/components/device-item/device-item.component.scss
  modules/ui/src/app/components/device-item/device-item.component.spec.ts
  modules/ui/src/app/components/device-tests/device-tests.component.scss
  modules/ui/src/app/components/program-type-icon/program-type-icon.component.ts
  modules/ui/src/app/pages/devices/devices.component.html
  modules/ui/src/app/pages/devices/devices.component.scss
  modules/ui/src/theming/mixins.scss
Labels: ui

#1070 388235982: (fix) setting and callout fixes
  modules/ui/src/app/components/callout/callout.component.scss
  modules/ui/src/app/pages/settings/settings.component.ts
Labels: ui

#1072 385169778: (feat) apply search for devices
  modules/ui/src/app/components/list-layout/list-layout.component.ts
  modules/ui/src/app/model/layout-type.ts
  modules/ui/src/app/pages/devices/devices.component.html
  modules/ui/src/app/pages/devices/devices.component.ts
Labels: ui

#1077 392037156: (fix) [GM3] close form after delete device
  modules/ui/src/app/pages/devices/devices.component.ts
Labels: ui

#1079 No warning popup appeared upon clicking on the ´ Create New Device ´ button and on another page when editing the device
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
  modules/ui/src/app/pages/devices/devices.component.html
  modules/ui/src/app/pages/devices/devices.component.ts
Labels: ui

#1086 Adds column order in testing table; adds missing icons for statuses
  modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.html
  modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.scss
  modules/ui/src/index.html
  resources/report/test_report_styles.css
  resources/report/test_report_template.html
Labels: ui

#1090 391367079: (feat) [GM3] [Risk profiles] add empty state
  modules/ui/src/app/components/empty-message/empty-message.component.html
  modules/ui/src/app/components/empty-message/empty-message.component.scss
  modules/ui/src/app/components/empty-message/empty-message.component.ts
  modules/ui/src/app/components/empty-page/empty-page.component.html
  modules/ui/src/app/components/empty-page/empty-page.component.ts
  modules/ui/src/app/components/list-layout/list-layout.component.scss
  modules/ui/src/app/model/layout-type.ts
  modules/ui/src/app/pages/devices/devices.component.html
  modules/ui/src/app/pages/devices/devices.component.scss
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
  modules/ui/src/assets/icons/empty-profiles.svg
  modules/ui/src/styles.scss
  modules/ui/src/theming/mixins.scss
Labels: ui

#1091 Adds layout for Risk profiles page
  modules/ui/src/app/components/list-layout/list-layout.component.html
  modules/ui/src/app/components/list-layout/list-layout.component.ts
  modules/ui/src/app/model/profile.ts
  modules/ui/src/app/pages/devices/devices.component.html
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
  modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
  modules/ui/src/assets/icons/draft.svg
  modules/ui/src/assets/icons/score.svg
  modules/ui/src/styles.scss
  modules/ui/src/theming/colors.scss
Labels: ui

#1092 Devices: The <Create New Device> to be disabled upon creating new device
  modules/ui/src/app/components/list-layout/list-layout.component.html
  modules/ui/src/app/components/list-layout/list-layout.component.scss
  modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
  modules/ui/src/app/pages/devices/devices.component.html
  modules/ui/src/app/pages/devices/devices.component.ts
Labels: ui

#1056 Add a disclaimer about tests affected by single interface mode
  docs/get_started.md
Labels: docs
